### ISSUE TITLE
Solidify method-type Tasks / runnable Collections concepts

### ISSUE THREAD

**Issue by bitprophet** [pyinvoke/invoke#347]
## Background

Branching this off of #199 pending whether I merge it as a PR, since I always end up regretting putting generic feature discussion on a specific patchset =/

Prior art / notes:

* [this comment](https://github.com/pyinvoke/invoke/pull/199#issuecomment-163826725) on #199 
* fabric/fabric#573
* #170 - which would need to encompass both the module-level-function and class-or-instance-method use cases

## To do

For me mostly.

* [ ] Reread all of #199, discussion & patchset, because sophacles has good ideas
* [ ] Square that with what's in my head at the moment & bang out some real-world-esque example user code / use cases, for use in evaluating #199 or other ideas
    * [ ] Invoke-only, local-only stuff like build pipelines
    * [ ] Fabric-2-related, ssh-including stuff like adding deployment to the above, wholly-remote config-management type things, etc
    * [ ] Other?
* [ ] Decide whether to use #199's patchset as a jumping off point or if I'd rather go in a different direction
* [ ] Write conceptual docs based on the previous bullet points
* [ ] Actually merge or implement something prior to 1.0 so users can start playing with it
* [ ] Solidify API for 1.0 (doesn't have to be perfect, can always tweak in a not-forever-from-now 2.0) & close

**Comment by joystein** [comment]
I have been using [fabric-taskset](https://github.com/kmike/fabric-taskset) with fabric for many years now and could hardly imagine using fabric without class-based task sets. It would be great to see this functionality built directly into invoke.

**Comment by tuukkamustonen** [comment]
There's a difference in classes as tasks (implementing `__call__` at simplest) and _tasksets_ (class containing several tasks). Just pointing it out.

To have something to begin with, simply being able to use methods (instead of functions) as tasks would be really nice. As per https://github.com/pyinvoke/invoke/pull/199 supporting that would seem like a minor adjustment?

I think the biggest advantage of class-based tasksets is being able to override annoying parts in a sub-class (assuming tasks call util methods that you can override etc.). Or care to elaborate the reasons why you like `fabric-taskset` @joystein ?

**Comment by bitprophet** [comment]
@tuukkamustonen To be fair, the difference isn't that large (at least, in my head, without having actually dug into either in detail) - whether a class represents "one task, with multiple non-task-exposed subroutines" or "one collection of tasks (or taskset), with some default task that gets called when you call the collection itself" seems to only boil down to whether those individual parts can be called as individual tasks, or if they're hidden.

In both cases, subclassing becomes the compelling way of overriding behavior, and that overall approach is the main driver for this feature, as I understand it. (E.g. "implement deployment of an app, allowing subclass+override to tweak platform details", or whatever.)

**Comment by tuukkamustonen** [comment]
Just to hint what I would like to have, something like:

```python
class PackagingTasks:

    def __init__(self, ns: Collection, config: dict,
                 include: List[callable] = None, exclude: List[callable] = None):
        if include:
            collection = Collection(*include)
        elif exclude:
            collection = Collection(*(t for t in self.collect_tasks() if t not in exclude))
        else:
            collection = Collection(*self.tasks)
        # And/or maybe exclude/include some tasks based on configuration given...
        ns.add_collection(collection, name='pkg')
        ns.configure({'pkg_config': config})

    def collect_tasks(self):
        return # return all @task decorated-methods

    @task
    def task1(self, ctx):
        pass

    @task
    def task2(self, ctx):
        pass
```

Then in `tasks.py`:

    ns = Collection()
    PackagingTasks(ns, {...}, exclude=[PackagingTasks.task2])

What do you think of this? I think the only thing missing from making this work is being able to annotate methods as `@task`?

**Comment by bitprophet** [comment]
@tuukkamustonen I find that a bit confusing, is the intent to import `PackagingTasks` into various `tasks.py` files, and instantiate it with different `include`/`exclude` values to tweak which tasks that particular instance exposes?

I recognize that one might want to do that, though it's IMO a more specific use case on top of the generic one being described in this ticket (which is just, a 'static' set of tasks organized in a class, same as a 'static' `tasks.py` is today.) And maybe this is just because it's a quick example, but I'm not sure I like the 'side effect' nature of that API, I feel like it'd be cleaner to end up returning a Collection object for use as `ns`, instead of mutating an existing `ns`.

----

Re: the general idea around tasks-as-methods, it was that `MethodCollection` is a subclass of `Collection` (could also simply be an alternate mode of use of regular `Collection`, if we updated it directly) whose `self.tasks` is, somehow, filled in with "all methods on `self` that were decorated with `@task`".

So that generic case might look like this (and it's quite possible one of the handful of PRs and branches already open about this, looks this way, I haven't dug):

You'd probably store the tasks in their own modules for easier reuse, say `packaging.py` for this one:

``` python
from invoke import Collection, task

class Packaging(Collection):
  name = 'packaging'
  @task
  def task1(self, c):
    pass

  @task
  def task2(self, c):
    pass
```

Then a basic `tasks.py` that _only_ cares about that one packaging namespace, could just do this:

``` python
from .packaging import Packaging

ns = Packaging()
```

Exposed tasks would be `task1, task2` at top level.

Or if you're mixing it into some other site-specific tasks, maybe:

``` python
from invoke import Collection, task
from .packaging import Packaging

@task
def build_my_stuff(c):
  pass

ns = Collection(build_my_stuff, Packaging())
```

Exposed tasks would be `build-my-stuff, packaging.task2, packaging.task2`.

----

In your case, I'd argue the probably-best approach is not to define one large collection and then 'filter' what's exposed, but instead to define the bits you would be filtering as discrete sub-collections, and compose them together as necessary (since Collections are, by their nature, trees.)

If you're able to implement your needs in that pattern, then there's no need for include/exclude - simply having the Collection modifications I noted above are sufficient, and then you can either use Collection composition, or subclassing, or a mix of both, to end up with what you need.

But this is all me spitballing without knowing your real use case :) all the "a bunch of methods in a class" use cases I can think of tend to be situations where one wants to compose or subclass-and-override. So I'm interested to hear more.

**Comment by tuukkamustonen** [comment]
Sorry for being too vague.

> is the intent to import PackagingTasks into various tasks.py files, and instantiate it with different include/exclude values to tweak which tasks that particular instance exposes?

Yeah, the idea would be to be able to customize what tasks are actually enabled (or revealed, rather) on two levels:

1. The taskset decides for you (e.g. if you're running python 2.x and not 3.x, then "mypy" task would be automatically excluded. Maybe mypy check works on comment-syntax as well, I just never tried, but let's say it doesn't so we can hold this as an example).
2. Caller must be able to manually include/exclude tasks (if taskset reveals a task you just have no use for, you must be able to exclude it. Or maybe you want to completely override what tasks taskset reveals so you manually include something that would be otherwise excluded - this is just for flexibility).

> I feel like it'd be cleaner to end up returning a Collection object for use as ns, instead of mutating an existing ns.

I kinda followed Flask's style of using middleware there. As you recall, in Flask this is how you include middleware:

    app = Flask(...)
    SomeMiddleware(app)

It works, it's simple for the caller and middleware gets full access to the Flask `app` object, so it can register whatever is needed. It may look scary to the caller, but middleware don't normally do bad things so you're safe :)

---

What you suggest here looks nice and clean but I think it's too limited:

1. Configuration and tasks go hand in hand. Taskset needs to get configuration on initialization time, so it can decide behavior (what tasks to reveal, at least) on initialization. How would you pass configuration in your examples (if it's not set via ENV variables or such)? 
2. Allow manually include/exclude tasks (so to override built-in behavior - use cases vary and not everyone is interested in seeing your 'superdupertask' even though you thought so).

---

> In your case, I'd argue the probably-best approach is not to define one large collection and then 'filter' what's exposed, but instead to define the bits you would be filtering as discrete sub-collections, and compose them together as necessary (since Collections are, by their nature, trees.)
> 
> If you're able to implement your needs in that pattern, then there's no need for include/exclude - simply having the Collection modifications I noted above are sufficient, and then you can either use Collection composition, or subclassing, or a mix of both, to end up with what you need.

Engineering-wise, that may sound sensible, but in practice it's just simpler to have one `PackagingTasks`, that automatically filters and reveals only related tasks to you, while allowing custom includes/excludes, instead of splitting it into `WheelPackagingTasks`, `SdistPackagingTasks`, `PackagingBuildingTasks`, `WheelPackagingBuildTasks` and whatever, just go get the same. That could even lead to having 1 task per class, rendering this feature useless(!)

> then you can either use Collection composition, or subclassing, or a mix of both, to end up with what you need.

What do you mean by sub-classing here - how would you hide/exclude a task in a sub-class in your `Packaging(Collection)` example?
